### PR TITLE
Add JSON output support.

### PR DESCRIPTION
**Pull request by teezzan**
This is a PR for the JSON feature of `scilla`. This is a work in progress and will be updated as it progresses.

### CODE REVIEW

**Comment by teezzan** [comment]
@edoardottt Is this alright? I am kinda new to this and read somewhere that PRs should be open for any work in progress.

**Comment by edoardottt** [comment]
perfect :)

**Comment by edoardottt** [comment]
perfect :)

**Comment by teezzan** [comment]
@edoardottt, Please check out [the AppendWhere](https://github.com/teezzan/scilla/blob/b45b1ad321a426b4dde216f2a19574183c65f238/output/file.go#L90) function. While this works for every thing except `dns`, I am faced with the question of adding another parameter to that function. What is your take on that?
This is because there is need to pass the dns records as keys too eg `SRV`.  Thanks for your help.

**Comment by edoardottt** [comment]
If I understood the problem it's okay and I think it's the most clever way to solve this. Just pass another (optional) parameter and the function will use it only if the file type is JSON and the key is DNS. Am I wrong?...

**Comment by teezzan** [comment]
Yup, that would solve it. I will do that.
Thanks

**Comment by teezzan** [comment]
Please Check it out

**Comment by edoardottt** [comment]
Sorry I was sleeping :/ ahahah. Everything okay :)

**Comment by teezzan** [comment]
Alright. Thanks. What's the next thing to do?

**Comment by edoardottt** [comment]
Well I think you can start working on `json.go` file adding the key features, like writing the results into the file.  
Maybe it's better to start with the easiest ones (directories, ports and subs) and then pass to dns.  
What do you think ??

**Comment by teezzan** [comment]
I think I already did that. I am able to write to the file the result of a scan. Is it possible that I'm missing something?

**Comment by edoardottt** [comment]
I didn't see [this line](https://github.com/edoardottt/scilla/pull/35/files#diff-9a9e4fb65ebdd454d7bae4fa82feecf23b8b3b48ae1f4149bf71e8b5275b4b1eR70). right.

So, I'm gonna approve the pr and then if there are changes to do I will open an issue, ok? :+1:

**Pull request merged**
