### PR TITLE
improvement: updated spyse module with rate-limiting support, added deep pagination

### PR DESCRIPTION
**Pull request by pokerok**
Hi there,
I maid spyse integration update due to changes in go-spyse lib:
- we added requests rate-limiting to avoid too_many_requests error.

Also, I added deep pagination to increase the count of subdomains search results, but I made limiting to 20k results because there is can be more than 1 million results and we cannot currently limit their number in any way. 

Please get in touch with me if you need a free Spyse API token to test the PR.
Best regards.

### CODE REVIEW

**Comment by edoardottt** [comment]
Hi @pokerok !  
Thank you so much for this pr.  

I've change the base branch to `devel` because I would like to test before commit into the `main` branch.  

And yes, I'm also interested in a free token. :+1:   
Thank you another time for the p.r.

**Comment by pokerok** [comment]
For some reason I didn't see this branch, thanks.

**Comment by edoardottt** [comment]
Sorry @pokerok to bother you.  
I think I have a problem. When I use curl with the token you provided me I get back a lot of info and this is ok, *i think* it's not a problem related to the token.

Instead when I use this Go code I *always* get a fatal error like this `YYYY/MM/DD hh:mm:ss code:too_many_requests message:"too many requests"`.  

I think the problem is the rate limit of 2 reqs/sec. When it's executed [this line](https://github.com/edoardottt/scilla/blob/devel/opendb/spyse.go#L80) or [this one](https://github.com/edoardottt/scilla/blob/devel/opendb/spyse.go#L107) (in the case of length of results <= 10k), since those lines are in a infinite for loop, it will perform way more than 2 reqs/sec.

Could be this the issue?

**Comment by pokerok** [comment]
It's okay, you can write at any time. 
I'll check it out now, thanks for letting me know.

**Comment by edoardottt** [comment]
@pokerok any update?

**Pull request merged**
